#!/bin/sh

path=$(dirname "$(readlink -f "$0")")
checker="${path}/"*.py

if [ ! -x "$checker" ]; then
	echo "Error: '$checker' not found or executable." >&2
	echo "Internal error"
	exit 1
fi

test_input="$1"
test_output="$2"
feedback_dir="$3"
message_file="${feedback_dir}/judgemessage.txt"

# Run the program:
"$checker" "$test_input" "$test_output" < /dev/stdin > "$message_file"
exit_code=$?

# Exit with failure, when non-zero exitcode found:
if [ $exit_code -ne 0 ]; then
	echo "Error: '$checker' exited with exitcode $exit_code." >&2
	echo "Internal error"
	exit 1
fi

# Check result and write result file:
if [ -s "$message_file" ]; then
	exit 43 # Wrong answer
fi
exit 42 # Correct