#!/bin/sh

path=$(dirname "$(readlink -f "$0")")
checker=$(find "${path}" -name "*.py" -print)

if [ ! -f "$checker" ]; then
	echo "Error: '$checker' not found." >&2
	echo "Internal error"
	exit 1
fi

test_input="$1"
test_output="$2"
feedback_dir="$3"
message_file="${feedback_dir}/judgemessage.txt"

# Run the program:
python3 "$checker" "$test_input" "$test_output" "$feedback_dir" < /dev/stdin > "$message_file"
exit_code=$?

if [ $exit_code -eq 42 ] || [ $exit_code -eq 43 ]; then
  exit $exit_code
fi

echo "Error: '$checker' exited with unexpected exitcode $exit_code." >&2
echo "Internal error"
exit 1
