volumes:
  domjudge_mariadb_data: {}
  domjudge_mariadb_backup: {}

networks:
  domjudge:
    driver: bridge

x-judgehost-config: &judgehost-config
  image: incaseoftrouble/judgehost:latest
  cgroup: host
  restart: on-failure
  networks:
    - domjudge
  depends_on:
    - domserver
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
  privileged: true
  environment:
    CONTAINER_TIMEZONE: ${TZ}
    JUDGEDAEMON_USERNAME: judgehost
    JUDGEDAEMON_PASSWORD: ${DOMJUDGE_JUDGE_PASSWORD:?}
    DOMSERVER_BASEURL: http://domjudge/

services:
  domjudge_mariadb:
    container_name: domjudge_mariadb
    image: mariadb:12
    command: --innodb_snapshot_isolation=OFF --max-connections=1000 --innodb-log-file-size=2G --max-allowed-packet=1G --net_read_timeout=3600 --net_write_timeout=3600
    networks:
      - domjudge
    ports:
      - 3306:3306/tcp
    volumes:
      - domjudge_mariadb_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DOMJUDGE_DB_ROOT_PASSWORD:?}
      MARIADB_USER: domjudge
      MARIADB_PASSWORD: ${DOMJUDGE_DB_DOMJUDGE_PASSWORD:?}
      MARIADB_DATABASE: domjudge

  domjudge-mariadb-backup:
    container_name: domjudge_mariadb_backup
    image: fradelg/mysql-cron-backup:1.14.1
    networks:
      - domjudge
    volumes:
      - domjudge_mariadb_backup:/backup
    restart: unless-stopped
    environment:
      MYSQL_HOST: domjudge_mariadb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: ${DOMJUDGE_DB_ROOT_PASSWORD:?}
      CRON_TIME: "12 */6 * * *"
      MAX_BACKUPS: 12
      INIT_BACKUP: 1
      TZ: ${TZ}

  domserver:
    container_name: domjudge
    image: incaseoftrouble/domserver:latest
    networks:
      - domjudge
    ports:
      - 12345:80/tcp
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: domjudge_mariadb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: domjudge
      MYSQL_PASSWORD: ${DOMJUDGE_DB_DOMJUDGE_PASSWORD:?}
      MYSQL_DATABASE: domjudge
      CONTAINER_TIMEZONE: ${TZ}
      DJ_DB_INSTALL_BARE: 1

  judgehost:
    <<: *judgehost-config
    container_name: judgehost
    hostname: judgehost
    environment:
      DAEMON_ID: 1