#!/bin/sh

destination="$1"
# memory_limit="$2"
shift 2
# main_source="$1"

temp_dir="$(mktemp -d --tmpdir=$(pwd) javac_output.XXXXXX)" || exit 1
export TMPDIR="${temp_dir}"
rustc --cfg 'DOMJUDGE' -C opt-level=3 -o "$destination" --crate-type bin --edition=2024 "$@"
rustc_exit_code=$?
rm -rf "${temp_dir}"
exit $rustc_exit_code